### ISSUE TITLE
Tried 0.14.0 with every versions of otel-java out there, did not work

### ISSUE THREAD

**Issue by rubenfiszel** [GoogleCloudPlatform/opentelemetry-operations-java#103]
Followed the instructions here: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/exporters/auto/README.md

otel-java 1.0.1 and 1.0.0: the gcp exporter does not seem to be picked up
otel-java 0.17.0:
```
Exception in thread "BatchSpanProcessor_WorkerThread-1" java.lang.NoSuchMethodError: 'io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.Span$Kind io.opentelemetry.sdk.trace.data.SpanData.getKind()'
```

**Comment by jsuereth** [comment]
0.14 was only released against the 1.0 API/SDK (not the auto instrumentation/agent).  I'll be cutting 0.15 shortly that should cut shortly.

In the meantime, can you let me know which version of these artifacts you want?

- [io.opentelemetry :: opentelemetry-api](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-api/1.1.0/jar) ([this project](https://github.com/open-telemetry/opentelemetry-java))
- [io.opentelemetry.javaagent :: opentelemetry-javaagent](https://search.maven.org/artifact/io.opentelemetry.javaagent/opentelemetry-javaagent/1.0.1/jar) ([this project](https://github.com/open-telemetry/opentelemetry-java-instrumentation))


Note: Our exporter for the Java Instrumentation agent is still in "alpha" / "experimental" phase.

**Comment by rubenfiszel** [comment]
@jsuereth Thanks! Any version as long as the auto-instrumentation part work. I am trying to use it as an experimental project so we do not have requirements and we will migrate to otel as soon as auto-instrumentation work with cloud trace with the versions that you recommend.

**Comment by jsuereth** [comment]
Ok, 0.15.0 should be out please give it a try.

**Comment by jsuereth** [comment]
Closing for now, please reopen if you still see issues with 0.15
