### ISSUE TITLE
sample launch command in documentation is no longer correct for v1.x of opentelemetry-javaagent.jar

### ISSUE THREAD

**Issue by kb99** [GoogleCloudPlatform/opentelemetry-operations-java#106]
v1.0 of the opentelemetry-java-instrumentation project has changed the property
otel.exporter.jar -> otel.javaagent.experimental.exporter.jar

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2486

the `readme.md` needs to be updated to reflect this

`java -javaagent:path/to/opentelemetry-javaagent-<version>-all.jar \
     -Dtel.javaagent.experimental.exporter.jar=path/to/opentelemetry-operations-java-auto-<version>.jar \
     -jar myapp.jar`

**Comment by jsuereth** [comment]
There's still a lot of churn in the loading aspect of auto instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2881

I'll make sure to denote this feature ONLY works with the specified version
