### ISSUE TITLE
Make it possible to disable metric exporter when using auto-instrumentation

### ISSUE THREAD

**Issue by cho0o0** [GoogleCloudPlatform/opentelemetry-operations-java#116]
When using `exporter-auto-0.15.0-alpha.jar` combined with `opentelemetry-javaagent`, it is seemingly impossible to only enable Cloud Trace Exporter (with Metrics Exporter disabled).
To add an option (e.g. environment variable) or to distribute the exporters separately will be very helpful.

**Comment by jsuereth** [comment]
We're migrating these to the autoconf module in Otel Java.  Here you'll be able (and required) to configure them separately.

**Comment by jsuereth** [comment]
Once the 1.5.0 release of isntrumentation is out, you can migrate to the 0.16.0 version of GCP exporters and you can (only) piecemeal enable/disable exporters.

**Comment by cho0o0** [comment]
Seems like 0.16.0 is out now. I will have a try. Thank you so much for the release.
