### ISSUE TITLE
Question: where is maven repository with latest release 0.16.0?

### ISSUE THREAD

**Issue by vtajzich** [GoogleCloudPlatform/opentelemetry-operations-java#119]
There is latest release 0.16.0 (https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/releases/tag/v0.16.0). 

However, I can't find it in maven repository: https://search.maven.org/artifact/com.google.cloud.opentelemetry/exporter-auto

Could you point me to the right repository or publish it?

**Comment by jsuereth** [comment]
`exporter-auto` is an alpha release right now, due to instability in upstream opentelemtery-java SPIs.  You can find it here:

https://search.maven.org/artifact/com.google.cloud.opentelemetry/exporter-auto/0.16.0-alpha/pom

Specifically, make sure you're using 0.16.0-alpha as your version.
