### ISSUE TITLE
Auto jar lost trace data in cloud run

### ISSUE THREAD

**Issue by luaifei** [GoogleCloudPlatform/opentelemetry-operations-java#129]
Have already set up the openTelemetry Auto instrumentation agent and auto exporter in Cloud run. It works well to export trace data into Cloud trace. But I find that not all trace data will be sinked into cloud trace. Any possible actions to avoid it?
I guess that the limitation is from Cloud run because it doesn't support the background activity. If so, can we provide any ways to support it well in Cloud run? Thanks ahead.

**Comment by jsuereth** [comment]
So, I've been looking into various possible reasons this could happen.  There's a few:

- Cloud Run exits the process before spans can be exported.  (You can use different settings in your service to limit the likelihood of this)
- You're sampling traces:
  - You're using Parent-based sampling and the incoming trace-sampled flag is 0 (i.e. don't sample)
  - You're using a probability sampler
  
Generally, for this kind of scenario we recommend doing one of two things:

1. Catch [SIGTERM](https://cloud.google.com/run/docs/reference/container-contract#instance-shutdown) and export all telemetry during the 10 second grace period (preferred).   IIUC, given shutdown hooks in the JVM agent, this should already be happening.  If this isn't the case, we may need to add a specific sigterm handler in the agent (or add one via google's extension) that makes sure cloud run knows SIGTERM is being handled to initiate the 10 second grace period.
2. Use "simple" span processor and flush spans immediately, during the control flow of the RPC execution.  This has a larger runtime overhead, and relies on access to a *very* local collector or other agent to collect and report spans in batches.  In GKE-world this would be a sidecar, for cloud-run it's a bit more complicated at the moment.

Not sure this is exactly what you're looking for, but this is our current recommendation.
