### ISSUE TITLE
Use openTelemetry for exporting Metrics

### ISSUE THREAD

**Issue by amroakmal** [GoogleCloudPlatform/opentelemetry-operations-java#133]
Hello.

I have a list/array that have some metrics calculated for memory usage and CPU, and some others.
What I need is simple, I want to use openTelemetry to export these metrics to Google Cloud to be able to get some statistics about that data such as mean, distribution and so on.

I'm lost in the documentation, and the code is not clear at all for me.

Any guidance, please on how to achieve this?

Thanks!

**Comment by jsuereth** [comment]
Unfortunately, I have 1 quick question:

   Are you using GCE, GKE or Cloud Run/Cloud Functions?
   
 The best guide follows from there.

**Comment by punya** [comment]
@amroakmal we'd love to point you to better documentation -- would you mind telling us where your code is running (GCE, GKE, Serverless, or local dev)?

**Comment by punya** [comment]
@amroakmal my apologies, I dropped the ball on this issue. Please reopen if it's still relevant to you.
