### ISSUE TITLE
otel metrics API is stable, but the docs here suggest otherwise

### ISSUE THREAD

**Issue by eli-jordan** [GoogleCloudPlatform/opentelemetry-operations-java#136]
Per https://opentelemetry.io/status/ the metrics API is now stable. However, the [metrics readme](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/exporters/metrics/README.md) indicates otherwise.

Is the metrics support in this library feature complete / compatible with the stable metrics API from otel?

**Comment by jsuereth** [comment]
Fixiing it now.  We are now launching a new version that leverages the stable metrics API

(Note: the SDK is still not marked stable)
