### ISSUE TITLE
Something is wrong with my agent configuration: Resource attributes are missing

### ISSUE THREAD

**Issue by nicklocaso** [GoogleCloudPlatform/opentelemetry-operations-java#152]
Like I said on [this issue](https://github.com/open-telemetry/opentelemetry-java/issues/4448) I have a problem exporting attributes like "service.name" with Java JAR [opentelemetry-javaagent.jar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases) and Java JAR [google-exporter-auto](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto).

Traces are here but without reference to service.name

`java -javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.extensions=exporter-auto.jar -Dotel.traces.exporter=google_cloud_trace -Dotel.metrics.exporter=none -Dotel.logs.exporter=none -Dotel.resource.attributes=service.name=shifts-srv -jar ./shifts-srv-1.0-SNAPSHOT.jar`

What can be wrong?

**Comment by jsuereth** [comment]
What version of OpenTelemetry exporter are you using?

We've made a few (recent) releases where these attributes should now show up on traces.

**Comment by dashpole** [comment]
Feel free to reopen if you are still encountering issues.
