### ISSUE TITLE
Issue with metric descriptor type (workload.--) and metric labels

### ISSUE THREAD

**Issue by dgnemo** [GoogleCloudPlatform/opentelemetry-operations-java#155]
Hello,

could you provide more context on why all the metrics are exported with the descriptor type: `workload.googleapis.com`
See: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/c27ed8fe2cde16b3bda6583fa9bc49dad8ca6446/exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java#L51

On the Google Cloud documentation I could not find more information on this descriptor type, other that it's (reserved ?) for 
metrics automatically collected by the `G​K​E workload metrics pipeline`.
https://cloud.google.com/stackdriver/docs/solutions/gke/managing-metrics#workload-metrics

My understanding is that application-specific metrics should be recorder under `custom.googleapis.com` (https://cloud.google.com/monitoring/custom-metrics) or `external.googleapis.com` (https://cloud.google.com/monitoring/api/metrics_other#externalgoogleapiscom)

I am actually quite confused about this part, so any clarification would be very useful.

---

Currently the automatic usage of the metric descriptor type `workload.googleapis.com` is causing a failure in the library when a Metric uses a label of type INT64.  (In open-telemetry a datapoint with `Attributes.of(longKey("myLabel"), 1L)`

```
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT:
Field labels[0].valueType had an invalid value of "INT64":
Metric labels for this user-defined metric are required to be of type 'STRING': workload.googleapis.com
```

I tried to create a MetricDescriptor manually using GCloud api and I indeed noticed that Metric under `workload.googleapis.com` don't allow Labels with type INT64 (probably because those would not be supported by Prometheus / GKE workload metrics pipeline). Meanwhile metrics stored under `custom.googleapis.com` can have labels with type INT64.

---

Sorry for the long description.
Any guidance on the recommended descriptor type for user metrics, and how to prevent the failure above, would be very useful.
Thanks.

**Comment by dashpole** [comment]
Definitely a good question.  The domains have subtly different behavior due to some differences in how they are implemented on Google's end.  Generally speaking, `workload.googleapis.com` can be thought of as an improved version of `custom.googleapis.com`.  A few of the differences:

* Number of metric descriptors per-project (10k vs 25k): https://cloud.google.com/monitoring/quotas#custom_metrics_quotas
* custom.googleapis.com supports non-string-typed labels, but no other domain does.
* workload.googleapis.com does not support the `global` resource.
* workload.googleapis.com is append-only for metric descriptor labels (prevents a common foot-gun scenario).
* workload.googleapis.com will likely have some (to be announced) differences in the billing model from custom.googleapis.com.  It is currently not charged during the deprecation of GKE workload metrics.

workload.googleapis.com is used by GKE workload metrics, but is intended to be generally used for writing user-defined metrics, and is the recommended domain to write metrics to using OTel today.  The solution is probably to convert non-string labels to strings in our exporters.

**Comment by dgnemo** [comment]
Thanks for the clarification!

I guess I can update my application code to only use string-typed labels for now, and maybe the exporter can be updated as you described above to prevent issues to future users.

I am leaving the issue open to track the fix in the exporter.

**Comment by jsuereth** [comment]
Nominally, the API was supposed to be autoconverting integer labels to strings for us.   We can move that logic into the exporter (thanks for reporting).

I want to highlight @dashpole's comment on `workload.googleapis.com is append-only for metric descriptor labels (prevents a common foot-gun scenario).`.

The primary benefit (outside of others listed) for workload.googleapis.com is around the usage of MetricDescriptor and avoiding common bugs/issues.   Specifically with `custom.googleapis.com` we found many scenarios where users would update a metric on a server and have conflicting metric descriptors between servers.   This lead to point-loss from one stream or another (or across the board) as metric descriptors would churn.   Unfortunately, we've been stretch to the limits of our ability to fix this issue server side without breaking contract with existing `custom.googleapis.com` users.   Instead, `workload` has been rethought to ensure better MetricDescriptor experience for custom metrics, more inline with what you'd expect from, e.g. Prometheus usage (i.e. be as flexible as possible).

**Comment by gabroo** [comment]
Hello,

I have a very specific use case where I need metrics to be written with the `custom.googleapis.com` type, so I can read the time series from internal Monitoring. The `workload.googleapis.com` data is not written to Monarch (it uses a "veneer"), so it doesn't work. 

Unfortunately it seems there is currently no way to override this. 

The logic in this repo indicates that if you have a "known" domain in your instrument name, then it will not append the default `"workload.googleapis.com/"` prefix ([here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/60cf3d675eda0900258853d568c21bfd4d692d49/exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java#L139)). However, the validation rules in the core OTel library rejects any instrument names that contain `/` characters ([here](https://cs.github.com/open-telemetry/opentelemetry-java/blob/4eb968e0d46b158a6bb0ef7365ed8c30783be71e/api/all/src/main/java/io/opentelemetry/api/internal/ValidationUtil.java#L68)). This means I cannot create a URL-encoded metric type with `custom.googleapis.com` as the domain. 

Am I missing some other way to change the domain? Appreciate your help with this.

(As a side note, it seems GKE Workload metrics are [deprecated](https://cloud.google.com/stackdriver/docs/solutions/gke/workload-metrics). Not sure what the implication is for writing custom metrics to the domain.)

**Comment by dashpole** [comment]
@gabroo 

The workload.googleapis.com domain is still the recommended domain to use with this exporter despite the deprecation of the GKE workload metrics pipeline.

I've opened https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/186 to track supporting a prefix.
