### ISSUE TITLE
Correct way to name metrics

### ISSUE THREAD

**Issue by dgnemo** [GoogleCloudPlatform/opentelemetry-operations-java#156]
Google Monitoring has a concept of `PATH` for the metric name.
Example: `instance/cpu/utilization`
(see https://cloud.google.com/monitoring/api/v3/naming-conventions)

My understanding is that the PATH is used in the Monitoring UI to select metrics using hierarchy selector.

Unfortunately OpenTelemetry doesn't allow `/` forward-slashes in the metrics name.

```
Instrument names must consist of 63 or fewer characters
including alphanumeric, _, ., -, and start with a letter.
```

Is there a recommended way to bridge the OpenTelemetry model to Google Monitoring model, and take advantage of PATH / hierarchy in the metrics names ?

Thanks!

**Comment by dgnemo** [comment]
Instrument naming, in the OpenTelemetry Specification:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-naming-rule

**Comment by dgnemo** [comment]
actually it's possible that I misunderstood how `PATH` and the Google Monitoring UI would interact.
(I am not sure that there is a hierarchical view of the metrics, although it would be nice?)

Still it would be nice to reconcile the `PATH` described in the google documentation with the open-telemetry specification.

I am leaving this open in case anyone has comments or recommendations on this topic.

**Comment by jsuereth** [comment]
I think this is a very good suggestion.   Given how Metric Explorer works, allowing your natural hierarhcy to be represented by default in our UI is ideal.

In practice, I belive that `.` now leads to hierarchical viewing in addition to just `/`, so it may be a documentation fix on our end.  We are aware of the differneces between OTEL metric naming conventions and GCM's suggestions.   I'd recommend sticking with OTEL's and opening bugs where see friction so we can make sure the naming conventions are supported in GCM.

**Comment by damemi** [comment]
Ideally, this should just work from the Otel side, without having to be concerned about the metric naming. If we want, we can open a docs bug on the Cloud Monitoring side to be more clear about the conventions.
