### ISSUE TITLE
GCP log errors when otel.javaagent request for authentication

### ISSUE THREAD

**Issue by Son91Dev** [GoogleCloudPlatform/opentelemetry-operations-java#162]
Hi all,
I have got these below error logs after trying apply "Auto-Configuration for OpenTelemetry in Google Cloud".

![image](https://user-images.githubusercontent.com/109411550/189308696-09593c56-533d-420b-ab88-0afcaf8bf804.png)

My configuration is as below:
`ENV OTEL_TRACES_EXPORTER google_cloud_trace`
`ENV OTEL_METRICS_EXPORTER none`
`ENV OTEL_JAVAAGENT_EXTENSIONS ${DEPLOYMENT_DIR}/exporter-auto.jar`
`ENV JAVA_TOOL_OPTIONS -javaagent:${DEPLOYMENT_DIR}/opentelemetry-javaagent.jar`

Traces are still sent to Cloud Trace successfully but I get this error log for every 30 minutes.
Does anyone have any ideas about this?

**Comment by aabmass** [comment]
@Son91Dev can you add some more information:

- can you share a link to "Auto-Configuration for OpenTelemetry in Google Cloud"?
- what environment are you running this in?

It looks like possibly grpc is just logging at error level for a normal event.

**Comment by aabmass** [comment]
> It looks like possibly grpc is just logging at error level for a normal event.

Actually, I think the logging agent where this is running is interpreting the logs as errors even though I see `INFO` in the log message. I'm going to close this but please re-open if it is still an issue.
