### ISSUE TITLE
Create a new release for opentelemetry-operations-java

### ISSUE THREAD

**Issue by psx95** [GoogleCloudPlatform/opentelemetry-operations-java#188]
Need to create a new release for this repo which includes the more GCP environments supported for resource detection and upstream OpenTelemetry dependency updates. 

~This would also solve issues like - #141 .~

This would solve #184

**Comment by dashpole** [comment]
This is good to do.

**Comment by dashpole** [comment]
Please compare the MR mapping for java to go before this release

**Comment by gabroo** [comment]
When is this release expected to be pushed? Can you include #189 in it?

**Comment by psx95** [comment]
#189 will be included in the upcoming release. There is no specific date since its P2, but I would expect it in the next 2 weeks.
