### ISSUE TITLE
Update dependencies to remove OSS vulnerabilities

### ISSUE THREAD

**Issue by psx95** [GoogleCloudPlatform/opentelemetry-operations-java#191]
The following dependencies have either known OSS vulnerabilities or they depend on other artifacts with known vulnerabilities. 

These need to be bumped to versions that fix these vulnerabilities. 
 - com.google.cloud:google-cloud-core:2.0.5
 - com.google.cloud:google-cloud-trace:2.0.0
 - com.google.api.grpc:grpc-google-cloud-trace-v2:2.0.0
 - com.google.auto.service:auto-service:1.7.4
 - com.google.auto.service:auto-service-annotations:1.7.4

**Comment by aabmass** [comment]
triaged
