### ISSUE TITLE
Metrics Readme state

### ISSUE THREAD

**Issue by vemv** [GoogleCloudPlatform/opentelemetry-operations-java#236]
Hi there!

Thank you for your library.

I see that the [metrics exporter readme](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/c3ac980637dfeacdc1959d65c7010febe5a264bc/exporters/metrics/README.md) hasn't been touched in quite a while, and it has a couple prominent TODOs.

This doesn't inspire a lot of confidence, tbh!

Is this the right library to use at the moment? I want to send metrics to my Java app on GCP, using GCP's native offering. Don't know if there's a better-supported way at the moment.

I'd probably be fine with using alpha software (as marked by the READMEs) - I'd just need to know better about the points above.

Thanks - V

**Comment by psx95** [comment]
Hi @vemv,
Thank you for bringing up this issue, we will be using this issue to track the work for metrics exporter Readme file.

This library is being actively maintained and is the recommended approach to export used [OpenTelemetry](https://opentelemetry.io/docs/instrumentation/java/manual/) metrics to Google Cloud.

If your Java application uses OpenTelemetry to generate metrics, you should be able to use the exporter provided in this repo, if you use some other library to generate metrics, then you will have to make sure that the library supports exporting metrics to [Google Cloud Monitoring](https://cloud.google.com/monitoring/api/v3).

**Comment by vemv** [comment]
I don't happen to use GCP atm, but appreciated 🙌
