### ISSUE TITLE
Exporting does not work on Windows due to invalid metric description type name - backslash instead of slash

### ISSUE THREAD

**Issue by Eden90** [GoogleCloudPlatform/opentelemetry-operations-java#252]
Hello,
I'm trying to export metrics from Windows system. It seems like the metrics exporter library is generating invalid type name for the metric description. It concatenate prefix with the metric name using the backslash instead of slash what comes up with the below error.
```
INVALID_ARGUMENT: Field metricDescriptor.type had an invalid value of "custom.googleapis.com\example_counter": The metric type must be a URL-formatted string with a domain and non-empty path.
```

I found the code piece that is responsible for generating metric type name. It uses the Path object which uses internally default operating system file separator. That's the reason why it's not working on the Windows.
https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/74a108f594d081c7f059d32c6062a1add4d4b115/exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java#L229

I was looking for the easy work around but I couldn't find. Do you see any possibility for that?

**Comment by psx95** [comment]
Hi @Eden90, thank you for reporting this. 
This certainly looks like a bug and will be fixed in the next release. 

As for a workaround, the only thing I can think of - can you try running your application from within a linux based VM ? 

Or if switching OS is not an option, would containerizing your application via Docker help ?

**Comment by Eden90** [comment]
@psx95 I can't do that. Thanks for your PR!

**Comment by psx95** [comment]
Hi @Eden90, we plan to create a new release this week.
