### ISSUE TITLE
Logger name misspelled

### ISSUE THREAD

**Issue by arosien** [GoogleCloudPlatform/opentelemetry-operations-java#255]
[XCloudTraceContextPropagator](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/main/propagators/gcp/src/main/java/com/google/cloud/opentelemetry/propagators/XCloudTraceContextPropagator.java#L46) sets its logger name to `XCloudTraceContextPropogator` (`ogator` vs. `agator`). It should probably match.

**Comment by psx95** [comment]
Thank you for reporting this.

**Comment by arosien** [comment]
Also perhaps add the package name to the logger name.
