### ISSUE TITLE
Verify non-GKE resources map to `k8s_*` monitored resources

### ISSUE THREAD

**Issue by damemi** [GoogleCloudPlatform/opentelemetry-operations-java#258]
From https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/issues/627, verify that kubernetes resources do not require `cloud.platform: gcp_kubernetes_engine` to map to k8s Monitored Resources (`k8s_container`, `k8s_pod`, etc).

Go exporter/collector fix in https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/683 uses `k8s.cluster.name` resource attribute to identify a k8s resource. Other languages should be consistent with this.

**Comment by aabmass** [comment]
Triaged. If anyone would like to work on this please leave a comment.

**Comment by tkmsaaaam** [comment]
I created this PR. #340  Please review it.

**Comment by tkmsaaaam** [comment]
My apologize. I fixed this issue. But I noticed it contained bug. So I fixed it. Please review it.
https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/342
