### ISSUE TITLE
Map faas.* attributes to generic_task in resource mapping 

### ISSUE THREAD

**Issue by dashpole** [GoogleCloudPlatform/opentelemetry-operations-java#265]
Implement https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/pull/273 in the resource mapping in this repository.

**Comment by psx95** [comment]
Just to confirm, the ask here is to resolve https://github.com/GoogleCloudPlatform/opentelemetry-operations-python/issues/272 for the Java exporters, correct ?

Or is there any change in scope for this issue  ?

**Comment by dashpole** [comment]
Thats correct.  No change in scope

**Comment by psx95** [comment]
The Java exporter currently does not have mapping for `GENERIC_NODE`. I see that other language exporters have this mapping.

I think it would be great if we could update the scope of this issue to include that missing mapping as well.
