### ISSUE TITLE
Trace Exporter sets invalid parent span IDs for root spans

### ISSUE THREAD

**Issue by WadeGulbrandsen** [GoogleCloudPlatform/opentelemetry-operations-java#295]
Root spans should have the parent span ID left empty but Trace Exporter is setting them to `0000000000000000` which is not a valid span ID and shows up in Cloud Trace as `(Missing span ID 0000000000000000)`.

![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/assets/18219797/ba6a8131-6525-4975-a2fe-d7c38728f012)

I believe the issue is in [exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/70f129bfaf85e2bdd3975915f06ce9aa4e2b6806/exporters/trace/src/main/java/com/google/cloud/opentelemetry/trace/TraceTranslator.java#L123)

```java
if (spanData.getParentSpanId() != null) {
  spanBuilder.setParentSpanId(spanData.getParentSpanId());
}
```

Instead of checking to see if the parent span ID  is not null the check should be for if the parent context is valid:

```java
if (spanData.getParentSpanContext().isValid()) {
  spanBuilder.setParentSpanId(spanData.getParentSpanId());
}
```

After making that change to a local copy of the TraceTranslator.java I no longer see the `(Missing span ID 0000000000000000)` spans and the root span has the parent span ID empty.

![image](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/assets/18219797/d9d6c4c5-6dfb-4eb4-bdb0-58c34cd8f2c8)

**Comment by aabmass** [comment]
Thanks for the report and PR, we will take a look
