### ISSUE TITLE
Question: Where can I find this Jar opentelemetry-operations-java-auto-<version>.jar

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [GoogleCloudPlatform/opentelemetry-operations-java#320]
The document to configure auto instrumentation as given below specifies to use opentelemetry-operations-java-auto-<version>.jar 

java -javaagent:path/to/opentelemetry-javaagent.jar \
     -Dotel.javaagent.extensions=path/to/**_opentelemetry-operations-java-auto-<version>.jar_** \
     -Dotel.traces.exporter=google_cloud_trace \
     -Dotel.metrics.exporter=google_cloud_monitoring \
     -jar myapp.jar

Can someone please suggest from where to download this jar? Or is it the **shaded** (exporter-auto:0.27.0-alpha:shaded) or **auto** (exporter-auto:0.27.0-alpha) that is been referred here?

Document 
https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto

@psx95

**Comment by psx95** [comment]
The link to download is mentioned in the [README](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto#shaded-local-jar). 

Replace `<VERSION>` with the current latest release version number - `0.27.0` in the link address.

**Comment by psx95** [comment]
Yes, in the [auto-instrumentation section of the document](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto#autoinstrumentation-setup) the path mostly refers to the path of downloaded shaded auto-exporter jar.

You can use both shaded and non-shaded variants of the JAR, however when using with the Java agent we recommend using the shaded variant.

The JAR itself can have any name, you do not need to change the name to match the particular string mentioned in the README.
