### ISSUE TITLE
<Question> Cloud function Auto instrumentation query ? 

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [GoogleCloudPlatform/opentelemetry-operations-java#325]
Cloud function comes with out of the box auto instrumentation support can we override with Auto-Configuration for OpenTelemetry using the below approach to instrument our Java Cloud function?

https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto

**Comment by psx95** [comment]
1. Could you confirm what you mean by "out of the box auto instrumentation support" for Cloud Functions ?

2. Can you use [auto exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto) to export telemetry from a Cloud Function.
  - You should be able to, we don't have a sample for this particular use case though. Are you running into issues with this ?

**Comment by Santosh-Kumar-Perumal** [comment]
Could you confirm what you mean by "out of the box auto instrumentation support" for Cloud Functions ?
I mean to say I am able to see cloud trace for cloud function by default.

Can you use [auto exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto) to export telemetry from a Cloud Function?
You should be able to, but we don't have a sample for this particular use case. Are you running into issues with this ?
I was thinking to start integrating with [auto exporter](https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/tree/main/exporters/auto) but as the cloud function already sending the trace to cloud trace by default so wanted to check if we can over ride it with ato exporter

**Comment by psx95** [comment]
I'm not sure how the existing traces are being generated from the cloud function, but if you create OpenTelemetry Spans from your Cloud Functions code, you should be able to use auto-exporter to export it to Cloud Trace.
