### ISSUE TITLE
Try to cut a release and see if nebula release plugin is still working after upgrade

### ISSUE THREAD

**Issue by aabmass** [GoogleCloudPlatform/opentelemetry-operations-java#363]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/362 upgraded the nebula release plugin to fix a build issue. It's not clear if there were any breaking changes to the release process and we will need to cut a release to check.

**Comment by pintohutch** [comment]
Triaged and this issue is still valid. Will evaluate in the upcoming sprints.

**Comment by psx95** [comment]
I'll be doing a release this week.
