### ISSUE TITLE
Cloud Run Jobs are detected as gcp_compute_engine

### ISSUE THREAD

**Issue by psx95** [GoogleCloudPlatform/opentelemetry-operations-java#369]
Currently, workloads running as Cloud Run Jobs are being detected as GCP compute engine - this is because the resource detection does not support Cloud Run Jobs yet which leads to resource detection logic fall back to `gcp_compute_engine`.

Environment variables in a Cloud Run Job container differ from the environment variables set when the container is run as a Cloud Run Service.

Details around the differences between environment variables are documented [here](https://cloud.google.com/run/docs/container-contract#env-vars).

Update resource detection logic to support Cloud Run Job detection.

**Comment by dashpole** [comment]
I think we implemented something in Go.  We might want to duplicate that in java as well

**Comment by psx95** [comment]
Both PRs have been merged, the next release of the contrib repository should have the updated resource detector. Closing this issue.
