### ISSUE TITLE
README code throws compiler error

### ISSUE THREAD

**Issue by bhshkh** [GoogleCloudPlatform/opentelemetry-operations-java#372]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/f04d7e9588db98f227806b954bab726dae2981c9/exporters/trace/README.md?plain=1#L44 

Tried using the above lines but it shows error:

```
Required type:
TraceExporter
Provided:
SpanExporter
```

**Comment by psx95** [comment]
Thank you for reporting this, the readme needs to be updated. The method indeed returns a `SpanExporter` as it should.

I will update the README.
