### ISSUE TITLE
Build uber jar to make it easier to use "javaagent" integration

### ISSUE THREAD

**Issue by nilebox** [GoogleCloudPlatform/opentelemetry-operations-java#50]
Currently, having `exporter-auto` is not enough for enabling javaagent-based GCP exporters, you also need to manually bring all of its dependencies.

Publishing an "uber jar" Maven artifact (i.e. a single jar including all of dependencies) would solve that issue.

See comment thread https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/issues/47#issuecomment-722163492.

**Comment by zoercai** [comment]
https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/pull/51 added and released
