### ISSUE TITLE
Setup Maven release process

### ISSUE THREAD

**Issue by nilebox** [GoogleCloudPlatform/opentelemetry-operations-java#6]
We need a release process with publishing Maven artifacts for the end users to be able to add `opentelemetry-operations-java` as a dependency in their Java projects.

Overall the setup should be similar to https://github.com/census-instrumentation/opencensus-java, but using Circle CI, since that's what we are already using in [opentelemetry-operations-go](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/master/.circleci)

**Comment by cherryland** [comment]
bump

**Comment by nilebox** [comment]
For consistency with other `opentelemetry-operations-*` repositories, we should use Circle CI: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/master/.circleci
