### ISSUE TITLE
MetricExporter doesn't work with tags

### ISSUE THREAD

**Issue by zls88** [GoogleCloudPlatform/opentelemetry-operations-java#64]
I've got some code that can be simplified to something like this:

```
    private final LongCounter callCounter = meter.longCounterBuilder("opentelemetry_responses")
            .setDescription("number of responses returned")
            .setUnit("calls")
            .build();

        @Override
    public void filter(ContainerRequestContext containerRequestContext, ContainerResponseContext containerResponseContext) {
        String statusCode = "" + containerResponseContext.getStatus();
        String methodName = getMethodName(containerRequestContext);

        callCounter.add(1,
                Labels.of(
                        "status_code", statusCode,
                        "method", methodName));
    }
```

I expect it to be able to receive a bunch of combinations of tags and forward them to Stackdriver (presumably with different data). However I actually get an error like this:
```
ERROR [2021-01-05 22:54:01,024] com.google.cloud.opentelemetry.metric.MetricExporter: There should be exactly one point in each metricData, found 0
```
The above was emitted before any data was reported. If I report data, it will emit `There should be exactly one point in each metricData, found <N>` where `<N>` is the number of tag combinations I've reported.

Perhaps we need to iterate over all the points in the loop in `com.google.cloud.opentelemetry.metric.MetricExporter#export` and then perform the rest of the body of that method once per point?

**Comment by jsuereth** [comment]
FYI - Working on a fix for this.

**Comment by jsuereth** [comment]
FYI 0.14.0-RC1 is out (against OTel Java 0.14.1).  @zls88  Would you mind giving this a try and seeing if it fixes things?  I'd like to make sure we have this fixed before the 0.14.0 release if we can.

**Comment by zls88** [comment]
I'll try and test this in the next day or two and get back to you!

**Comment by jsuereth** [comment]
0.14.0-alpha version should fix this issue. Please reopen if you find that isn't the case.
