### ISSUE TITLE
Binary incompatibility when using Protobuf 2.x

### ISSUE THREAD

**Issue by scottsue** [GoogleCloudPlatform/opentelemetry-operations-java#67]
Protobuf 2.x and 3.x is well documented to be supported together in the future.  Digging into the dependencies of the Google Cloud Exporter shows there is a dependency on Protobuf 3.x.  This unfortunately excludes any projects that currently use Protobuf 2.x binary from using this exporter as there are binary incompatibilities between 2.x and 3.x.

A potential solution to this as suggested by @jsuereth would be to shade the Protobuf 3.x dependencies.

**Comment by jsuereth** [comment]
For reference, we're "shadowing" our autojar, which actually just means bundling all deps in it.

For this, we'd need to try to minimize + shift Protobuf/gRPC/Google Client libraries (see [Shadow Plugin Docs](https://imperceptiblethoughts.com/shadow/configuration/relocation/#filtering-relocation) for details).

I'm going to see if we can take a stab at this before Trace 1.0, but likely this will have to follow sometime later.

**Comment by damemi** [comment]
This seems like a more advanced use case that our team unfortunately doesn't have the capacity to support at the moment. Closing this as out-of-scope.
