### ISSUE TITLE
Question: Is this repo going to hold the official OpenTelemetry stack driver exporter for java?

### ISSUE THREAD

**Issue by eli-jordan** [GoogleCloudPlatform/opentelemetry-operations-java#7]
@nilebox There is [an issue](https://github.com/open-telemetry/opentelemetry-java/issues/663) open in the  opentelemetry-java repo indicating that vendor exporters will not be in the core repo.

This repo appears to be in the early stages of development. Will it become the official stack driver exporter for OpenTelemetry, or should I be looking somewhere else for that?

Also, I noticed there is currently no metrics exporter.

**Comment by nilebox** [comment]
@eli-jordan yes, this is the official place for OpenTelemetry -> Stackdriver (Cloud Monitoring / Trace) Exporters.

As you've already noticed, we don't have a stable version yet, but plan to release by the end of the next quarter (September 2020).
