### ISSUE TITLE
Publish auto jar

### ISSUE THREAD

**Issue by Tom-Fawcett** [GoogleCloudPlatform/opentelemetry-operations-java#72]
Hi :slightly_smiling_face: 

Is the exporter auto jar published anywhere? Currently I have been downloading it from CircleCI (e.g `exporter-auto-0.13.1-SNAPSHOT.jar`)

**Comment by jsuereth** [comment]
"com.google.cloud.opentelemetry:exporter-auto:0.11.0"

Is out on maven central (see: https://search.maven.org/search?q=a:exporter-auto)

We have not launched the latest (and a side note:  auto will be alpha even when the Trace exporter is 1.0 until we improve its test suite)

**Comment by jsuereth** [comment]
Better link: https://search.maven.org/artifact/com.google.cloud.opentelemetry/exporter-auto/0.11.0/jar

**Comment by Tom-Fawcett** [comment]
Thank you :slightly_smiling_face:
