### ISSUE TITLE
Support google.devtools.cloudtrace.v2.MessageEvent

### ISSUE THREAD

**Issue by humphrej** [GoogleCloudPlatform/opentelemetry-operations-java#91]
I am trying to convert the trace implementation of an application from OpenCensus to OpenTelemetry.  OpenCensus has a span.addMessageEvent method/class [1] that maps directly to the Google Trace MessageEvent [1] class.  

It looks like OpenTelemetry plans to use span.addEvent for this [3].  Are there plans to support this in the exporter?

[1] https://www.javadoc.io/static/io.opencensus/opencensus-api/0.18.0/io/opencensus/trace/Span.html#addMessageEvent-io.opencensus.trace.MessageEvent-
[2] https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v2#messageevent
[3] https://github.com/open-telemetry/opentelemetry-java/issues/13

**Comment by jsuereth** [comment]
> It looks like OpenTelemetry plans to use span.addEvent for this [3]. Are there plans to support this in the exporter?

Yes.  unfortunately, in OpenTelemetry `Events` map to both `Annotation` and `MessageEvent` on `TimeEvent`.   The plan is to use semantic conventions to understand when an `Event` is really a `MessageEvent`.  For now, all events should already be transmitted as `Annotation`s in `TimeEvent`s.

**Comment by damemi** [comment]
Closing as WAI
