### ISSUE TITLE
Map and export resource attributes in Tracing

### ISSUE THREAD

**Issue by nilebox** [GoogleCloudPlatform/opentelemetry-operations-java#93]
With GCE and GKE resource auto-detection implemented, both metrics and trace exporters will get these attributes which need to be mapped to GCP resource.

We have only implemented such mapping for metrics exporter: https://github.com/GoogleCloudPlatform/opentelemetry-operations-java/blob/fb34efb272b64414ddf0e2a5c881470bb0941887/exporters/metrics/src/main/java/com/google/cloud/opentelemetry/metric/MetricTranslator.java#L156-L171

As a follow-up work, we also need to port these changes to the trace exporter.

**Comment by jsuereth** [comment]
Note:  The ResourceProvider spi is pretty unstable in Java at this point (recently got reshuffled).  We should make sure this is aligned with the Autoconfigure SDK extension going stable, but we also may want to wait for upstream to figure out what it's doing so we limit churn in maintenance.

**Comment by michaelbannister** [comment]
Just wondering - how long will you want to wait to see how stable things are? I see `opentelemetry-java` went 1.0.0 and committed to semver on 26 Feb. I'm interested in using OTel with Trace and it'd be nice to get a bit more useful info (even just whatever the service.name attribute maps to) over in the Trace views.

**Comment by jsuereth** [comment]
Just an FYI - We've been tracking Otel Java pretty closely.   While the API for users is stable, things we rely on (specifically the resource SPI) has been shifting.  We need to do a few internal moves off deprecated components.   Likely this exporter won't be marked 1.0 until more components of Java SDK / ecosystem stabilize.

**Comment by damemi** [comment]
We aren't planning to add any more resource mapping at this time. The Cloud Trace team is planning to improve support for native Otel resource names.
